{% set name = "orsopy" %}
{% set version = "1.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/orsopy-{{ version }}.tar.gz
  sha256: 33364b18c04879035e16bcfe29e0cbcd9123570ca747ed1851ba943b124cf7ba

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - pyyaml >=5.4.1

test:
  imports:
    - orsopy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/reflectivity/orsopy
  summary: Support library of the Open Reflectometry Standards Organization (ORSO)
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - andyfaff
    - arm61
    - bmaranville
